/**
 * @file camera.c
 * @brief camera node: fill the camera/mipi config and call hbn_camera_create.
 *
 * The sensor is configured for externally triggered operation, so the frame sync is
 * generated by the LPWM trigger of vin_open() and both eyes expose in lockstep. The
 * function contract (parameters, units, ownership, return value) is documented with
 * the declaration in RDKS100.h.
 *
 * S100's camera_config_t and mipi_config_t carry more fields than X5's: the GPIO control
 * is named gpio_enable/gpio_level (against gpio_enable_bit/gpio_level_bit), an EEPROM and
 * a serializer address can be given, and both structures end with an end_flag that the
 * driver checks. Values that describe the module rather than the SoC (lane count, sensor
 * mode) are discussed where they are set below.
 *
 * This file is part of gs130_camera_sdk (https://github.com/D-Robotics/gs130_camera_sdk).
 * Copyright (c) 2026 D-Robotics.
 * SPDX-License-Identifier: MIT
 * See the LICENSE file in the project root for the full license text.
 */
#define _DEFAULT_SOURCE
#include "RDKS100.h"

#include <stdio.h>
#include <unistd.h>

/* RAW10, the sensor's output format. */
#define GS130_CAMERA_RAW10 0x2B

/* Number of MIPI lanes the sensor is wired with. 1 is what the existing X5 backend uses
 * for this module and it is a module property, so it is kept here; the platform's own
 * S100 table for sc132gs uses 2 lanes, but that table describes a different module. */
#define GS130_CAMERA_LANES 1

/*
 * Sensor mode index. The platform's S100 configuration for this exact sensor and size
 * (hobot_mipi_cam, src/s100/sensor/sc132gs_linear_1088x1280_raw10_30fps_1lane.c) selects
 * mode 1, which matches that file's linear 1088x1280 30fps description. The X5 backend
 * uses mode 6 and calls it the externally triggered mode; the two drivers have their own
 * mode tables, so the X5 index does not carry over.
 *
 * UNVERIFIED: whether mode 1 on S100 is also externally triggered has not been checked.
 * This is the first value to revisit during bring-up if the flow starts but no frame
 * arrives. See requirement-analysis/jira011-g3-revision.md.
 */
#define GS130_CAMERA_SENSOR_MODE 1

/**
 * @brief Drive the sensor reset GPIO: export it, then pulse the reset sequence.
 *
 * The GPIO is reached through sysfs. 1 -> 0 -> 1 is a reset sequence, not a power
 * switch: the rail stays on, the sensor is only released from reset. Every step of
 * the sequence is held for 30 ms.
 *
 * @param[in] gpio Reset GPIO number; a negative value returns 0 without touching sysfs.
 * @param[in] on   Non-zero runs the reset sequence, 0 drives the line low (no wait).
 * @return 0 when the sequence ran (or control is disabled), -1 when a value file cannot
 *         be opened.
 */
int sensor_power(int gpio, int on)
{
    if(gpio < 0)return 0;

    char path[64];
    FILE *fp;

    /* register the GPIO with sysfs, then set it up as an output */
    snprintf(path, sizeof(path), "%d", gpio);
    fp = fopen("/sys/class/gpio/export", "w");
    if (fp) { fputs(path, fp); fclose(fp); }

    snprintf(path, sizeof(path), "/sys/class/gpio/gpio%d/direction", gpio);
    fp = fopen(path, "w");
    if (fp) { fputs("out", fp); fclose(fp); }

    /* one character per step: "101" is the reset sequence, "0" keeps the line low */
    for (const char *p = on ? "101" : "0"; *p; ++p) {
        snprintf(path, sizeof(path), "/sys/class/gpio/gpio%d/value", gpio);
        fp = fopen(path, "w");
        if (!fp)
            return -1;
        fputc(*p, fp);
        fclose(fp);
        if (on)
            usleep(30 * 1000);
    }
    return 0;
}

int camera_open(camera_handle_t *cam_fd, uint8_t i2c_addr,
                uint32_t width, uint32_t height, uint32_t fps,
                uint32_t line_length, uint32_t frame_length,
                uint16_t mipiclk, uint16_t settle, uint16_t mclk,
                const char *tuning_file)
{
    /* MIPI receiver side: RAW10, one virtual channel, timing parameters handed in by the
       caller (see RDKS100.h). nocheck is enabled because the receiver is started by the
       sensor's own stream, as the platform's S100 configuration for this sensor does. */
    mipi_config_t mipi_cfg = {
        .rx_enable = 1,
        .rx_attr = {
            .phy = 0,                /* MIPI PHY index */
            .lane = GS130_CAMERA_LANES,
            .datatype = GS130_CAMERA_RAW10,
            .fps = (uint16_t)fps,
            .mclk = mclk,
            .mipiclk = mipiclk,
            .width = (uint16_t)width,
            .height = (uint16_t)height,
            .linelenth = (uint16_t)line_length,
            .framelenth = (uint16_t)frame_length,
            .settle = settle,
            .channel_num = 1,        /* one virtual channel */
            .channel_sel = {0},      /* virtual channel 0, matching vc_index in vin_open() */
        },
        .rx_ex_mask = 0x1,
        .rx_attr_ex = {
            .nocheck = 1,
        },
        .end_flag = MIPI_CONFIG_END_FLAG,
    };

    /* Sensor side; the exposure trigger is generated outside the sensor (LPWM, see vin_open()).
       The EEPROM and serializer addresses are left unset: this module is reached directly,
       and the addresses the platform's S100 table carries belong to its own module. */
    camera_config_t cam_cfg = {
        .name = "sc132gs",
        .addr = i2c_addr,
        .sensor_mode = GS130_CAMERA_SENSOR_MODE,
        .fps = fps,
        .format = GS130_CAMERA_RAW10,
        .width = width,
        .height = height,
        .extra_mode = 0,
        .config_index = 0,
        .mipi_cfg = &mipi_cfg,
        .gpio_enable = 0x01,         /* GPIO control bits handed to the driver; the reset */
        .gpio_level = 0x00,          /* line itself is pulsed by sensor_power() */
        .end_flag = CAMERA_CONFIG_END_FLAG,
    };
    snprintf(cam_cfg.calib_lname, sizeof(cam_cfg.calib_lname),
             "%s", tuning_file ? tuning_file : "disable");

    if (hbn_camera_create(&cam_cfg, cam_fd) != 0) {
        *cam_fd = 0;
        return -1;
    }
    return 0;
}
