/**
 * @file camera.c
 * @brief camera node: fill the camera/mipi config and call hbn_camera_create.
 *
 * The sensor is configured for externally triggered operation, so the frame sync is
 * generated by the LPWM trigger of vin_open() and both eyes expose in lockstep. The
 * function contract (parameters, units, ownership, return value) is documented with
 * the declaration in RDKX5.h.
 *
 * This file is part of gs130_camera_sdk (https://github.com/D-Robotics/gs130_camera_sdk).
 * Copyright (c) 2026 D-Robotics.
 * SPDX-License-Identifier: MIT
 * See the LICENSE file in the project root for the full license text.
 */
#define _DEFAULT_SOURCE
#include "RDKX5.h"

#include <stdio.h>
#include <unistd.h>

/**
 * @brief Drive the sensor reset GPIO: export it, then pulse the reset sequence.
 *
 * The GPIO is reached through sysfs. 1 -> 0 -> 1 is a reset sequence, not a power
 * switch: the rail stays on, the sensor is only released from reset. Every step of
 * the sequence is held for 30 ms.
 *
 * @param[in] gpio Reset GPIO number; a negative value returns 0 without touching sysfs.
 * @param[in] on   Non-zero runs the reset sequence, 0 drives the line low (no wait).
 * @return 0 when the sequence ran (or control is disabled), -1 when a value file cannot
 *         be opened.
 */
int sensor_power(int gpio, int on)
{
    if(gpio < 0)return 0;

    char path[64];
    FILE *fp;

    /* register the GPIO with sysfs, then set it up as an output */
    snprintf(path, sizeof(path), "%d", gpio);
    fp = fopen("/sys/class/gpio/export", "w");
    if (fp) { fputs(path, fp); fclose(fp); }

    snprintf(path, sizeof(path), "/sys/class/gpio/gpio%d/direction", gpio);
    fp = fopen(path, "w");
    if (fp) { fputs("out", fp); fclose(fp); }

    /* one character per step: "101" is the reset sequence, "0" keeps the line low */
    for (const char *p = on ? "101" : "0"; *p; ++p) {
        snprintf(path, sizeof(path), "/sys/class/gpio/gpio%d/value", gpio);
        fp = fopen(path, "w");
        if (!fp)
            return -1;
        fputc(*p, fp);
        fclose(fp);
        if (on)
            usleep(30 * 1000);
    }
    return 0;
}

int camera_open(camera_handle_t *cam_fd, uint8_t i2c_addr,
                uint32_t width, uint32_t height, uint32_t fps,
                uint32_t line_length, uint32_t frame_length,
                uint16_t mipiclk, uint16_t settle, uint16_t mclk,
                const char *tuning_file)
{
    /* MIPI receiver side: RAW10 on one lane, one virtual channel, timing parameters
       handed in by the caller (see RDKX5.h) */
    mipi_config_t mipi_cfg = {
        .rx_enable = 1,
        .rx_attr = {
            .phy = 0,                /* MIPI PHY index */
            .lane = 1,               /* lanes used by this sensor */
            .datatype = 0x2B,        /* RAW10 */
            .fps = (uint16_t)fps,
            .mclk = mclk,
            .mipiclk = mipiclk,
            .width = (uint16_t)width,
            .height = (uint16_t)height,
            .linelenth = (uint16_t)line_length,
            .framelenth = (uint16_t)frame_length,
            .settle = settle,
            .channel_num = 1,        /* one virtual channel */
            .channel_sel = {0},      /* virtual channel 0, matching vc_index in vin_open() */
        },
    };

    /* Sensor side; the exposure trigger is generated outside the sensor (LPWM, see vin_open()) */
    camera_config_t cam_cfg = {
        .name = "sc132gs",
        .addr = i2c_addr,
        .sensor_mode = 6,            /* externally triggered mode: LPWM drives the exposure trigger */
        .fps = fps,
        .format = 0x2B,              /* RAW10 */
        .width = width,
        .height = height,
        .mipi_cfg = &mipi_cfg,
        .gpio_enable_bit = 0x01,     /* GPIO control bits handed to the driver; the reset */
        .gpio_level_bit = 0x00,      /* line itself is pulsed by sensor_power() */
    };
    snprintf(cam_cfg.calib_lname, sizeof(cam_cfg.calib_lname),
             "%s", tuning_file ? tuning_file : "disable");

    if (hbn_camera_create(&cam_cfg, cam_fd) != 0) {
        *cam_fd = 0;
        return -1;
    }
    return 0;
}
